### ISSUE TITLE
회원가입 기능 제작

### ISSUE THREAD

**Issue by kgh2120** [kgh2120/jjiiim#9]
### 내용 : 고객과 점주의 회원 가입 기능을 제작한다
**관련 기능**
- 아이디 중복 검사
- 휴대폰으로 인증 토큰 요청
- 인증 토큰 검사
- 회원 가입

**TODO**
- [x] #10
- [x] #16
- [ ] Redis 설정 추가
- [ ] Spring Security 설정 추가
- [ ] 아이디 중복 검사 기능 추가
- [ ] 휴대폰 인증 토큰 요청 기능 추가
- [ ] 인증 토큰 검사 기능 추가
- [ ] 회원 가입 기능 추가
